spring.application.name=springmvc
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/Employee
spring.datasource.username=postgres
spring.datasource.password=krish
spring.jpa.hibernate.ddl-auto=update